
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.61.0.  DO NOT EDIT!
//*************************************************************************************

using System.Threading.Tasks;
using XTC.FMP.MOD.Vendor.LIB.Proto;

namespace XTC.FMP.MOD.Vendor.LIB.MVCS
{
    /// <summary>
    /// Blazor服务模拟类
    /// </summary>
    public class BlazorServiceMock
    {


        public System.Func<BlazorCreateRequest, Task<UuidResponse>>? CallCreateDelegate { get; set; } = null;

        public System.Func<BlazorUpdateRequest, Task<UuidResponse>>? CallUpdateDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<BlazorRetrieveResponse>>? CallRetrieveDelegate { get; set; } = null;

        public System.Func<UuidRequest, Task<UuidResponse>>? CallDeleteDelegate { get; set; } = null;

        public System.Func<BlazorListRequest, Task<BlazorListResponse>>? CallListDelegate { get; set; } = null;

        public System.Func<BlazorSearchRequest, Task<BlazorListResponse>>? CallSearchDelegate { get; set; } = null;

    }
}
