
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.70.0.  DO NOT EDIT!
//*************************************************************************************

using XTC.FMP.MOD.Vendor.LIB.Proto;
using XTC.FMP.MOD.Vendor.LIB.Bridge;

namespace XTC.FMP.MOD.Vendor.LIB.MVCS
{

    public class BlazorCreateRequestDTO : IDTO
    {
        public BlazorCreateRequestDTO(BlazorCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly BlazorCreateRequest Value;
    }



    public class BlazorUpdateRequestDTO : IDTO
    {
        public BlazorUpdateRequestDTO(BlazorUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly BlazorUpdateRequest Value;
    }



    public class BlazorRetrieveResponseDTO : IDTO
    {
        public BlazorRetrieveResponseDTO(BlazorRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly BlazorRetrieveResponse Value;
    }



    public class BlazorListRequestDTO : IDTO
    {
        public BlazorListRequestDTO(BlazorListRequest _value)
        {
            Value = _value;    
        }
        public readonly BlazorListRequest Value;
    }



    public class BlazorListResponseDTO : IDTO
    {
        public BlazorListResponseDTO(BlazorListResponse _value)
        {
            Value = _value;    
        }
        public readonly BlazorListResponse Value;
    }



    public class BlazorSearchRequestDTO : IDTO
    {
        public BlazorSearchRequestDTO(BlazorSearchRequest _value)
        {
            Value = _value;    
        }
        public readonly BlazorSearchRequest Value;
    }



    public class HealthyEchoRequestDTO : IDTO
    {
        public HealthyEchoRequestDTO(HealthyEchoRequest _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoRequest Value;
    }



    public class HealthyEchoResponseDTO : IDTO
    {
        public HealthyEchoResponseDTO(HealthyEchoResponse _value)
        {
            Value = _value;    
        }
        public readonly HealthyEchoResponse Value;
    }



    public class StatusDTO : IDTO
    {
        public StatusDTO(Status _value)
        {
            Value = _value;    
        }
        public readonly Status Value;
    }



    public class BlankRequestDTO : IDTO
    {
        public BlankRequestDTO(BlankRequest _value)
        {
            Value = _value;    
        }
        public readonly BlankRequest Value;
    }



    public class BlankResponseDTO : IDTO
    {
        public BlankResponseDTO(BlankResponse _value)
        {
            Value = _value;    
        }
        public readonly BlankResponse Value;
    }



    public class ScopeRequestDTO : IDTO
    {
        public ScopeRequestDTO(ScopeRequest _value)
        {
            Value = _value;    
        }
        public readonly ScopeRequest Value;
    }



    public class ScopeResponseDTO : IDTO
    {
        public ScopeResponseDTO(ScopeResponse _value)
        {
            Value = _value;    
        }
        public readonly ScopeResponse Value;
    }



    public class UuidRequestDTO : IDTO
    {
        public UuidRequestDTO(UuidRequest _value)
        {
            Value = _value;    
        }
        public readonly UuidRequest Value;
    }



    public class UuidResponseDTO : IDTO
    {
        public UuidResponseDTO(UuidResponse _value)
        {
            Value = _value;    
        }
        public readonly UuidResponse Value;
    }



    public class FileSubEntityDTO : IDTO
    {
        public FileSubEntityDTO(FileSubEntity _value)
        {
            Value = _value;    
        }
        public readonly FileSubEntity Value;
    }



    public class FileSubEntitySDTO : IDTO
    {
        public FileSubEntitySDTO(FileSubEntityS _value)
        {
            Value = _value;    
        }
        public readonly FileSubEntityS Value;
    }



    public class UnityEntityDTO : IDTO
    {
        public UnityEntityDTO(UnityEntity _value)
        {
            Value = _value;    
        }
        public readonly UnityEntity Value;
    }



    public class BlazorEntityDTO : IDTO
    {
        public BlazorEntityDTO(BlazorEntity _value)
        {
            Value = _value;    
        }
        public readonly BlazorEntity Value;
    }



    public class PrepareUploadRequestDTO : IDTO
    {
        public PrepareUploadRequestDTO(PrepareUploadRequest _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadRequest Value;
    }



    public class PrepareUploadResponseDTO : IDTO
    {
        public PrepareUploadResponseDTO(PrepareUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly PrepareUploadResponse Value;
    }



    public class FlushUploadRequestDTO : IDTO
    {
        public FlushUploadRequestDTO(FlushUploadRequest _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadRequest Value;
    }



    public class FlushUploadResponseDTO : IDTO
    {
        public FlushUploadResponseDTO(FlushUploadResponse _value)
        {
            Value = _value;    
        }
        public readonly FlushUploadResponse Value;
    }



    public class UnityCreateRequestDTO : IDTO
    {
        public UnityCreateRequestDTO(UnityCreateRequest _value)
        {
            Value = _value;    
        }
        public readonly UnityCreateRequest Value;
    }



    public class UnityUpdateRequestDTO : IDTO
    {
        public UnityUpdateRequestDTO(UnityUpdateRequest _value)
        {
            Value = _value;    
        }
        public readonly UnityUpdateRequest Value;
    }



    public class UnityRetrieveResponseDTO : IDTO
    {
        public UnityRetrieveResponseDTO(UnityRetrieveResponse _value)
        {
            Value = _value;    
        }
        public readonly UnityRetrieveResponse Value;
    }



    public class UnityListRequestDTO : IDTO
    {
        public UnityListRequestDTO(UnityListRequest _value)
        {
            Value = _value;    
        }
        public readonly UnityListRequest Value;
    }



    public class UnityListResponseDTO : IDTO
    {
        public UnityListResponseDTO(UnityListResponse _value)
        {
            Value = _value;    
        }
        public readonly UnityListResponse Value;
    }



    public class UnitySearchRequestDTO : IDTO
    {
        public UnitySearchRequestDTO(UnitySearchRequest _value)
        {
            Value = _value;    
        }
        public readonly UnitySearchRequest Value;
    }



}
