org_name: XTC
module_name: Vendor
generate:
  active: true
  database_driver: mongodb
  debug: false
  unity_solution: false
publish:
  active: true
  environment: develop
  repository: grpcs://api.xtech.cloud:29000
deploy:
  active: true
  environment: develop
  repository: grpcs://api.xtech.cloud:29000
  agent_port: 28002
