
//*************************************************************************************
//   !!! Generated by the fmp-cli 1.39.0.  DO NOT EDIT!
//*************************************************************************************

using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.IdGenerators;
using System;

namespace XTC.FMP.MOD.Vendor.App.Service
{
    public class BlazorEntity : Entity
    {
        public string Name { get; set; } = "";
        public string Display { get; set; } = "";
        public string Logo { get; set; } = "";
        public string SkinConfig { get; set; } = "";
        public string MenuTitle { get; set; } = "";
        public string MenuConfig { get; set; } = "";
        public string ModulesConfig { get; set; } = "";
    }
}
